# Numpy

In [3]:
from numpy.random import randn
import numpy as np

In [4]:
# 그래프를 바로 보기 위한 명령어
%matplotlib inline

In [5]:
data = randn(2, 3)
data

array([[ 1.11145582, -0.86635495,  0.11646437],
       [ 0.35487611,  0.39110746, -0.41229083]])

In [6]:
data.shape

(2, 3)

In [7]:
data.dtype

dtype('float64')

In [8]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.empty((2,3,2))

array([[[6.23042070e-307, 3.56043053e-307],
        [1.37961641e-306, 1.33508845e-306],
        [1.33511969e-306, 8.06610919e-308]],

       [[1.24610383e-306, 1.69118108e-306],
        [8.06632139e-308, 1.20160711e-306],
        [1.69119330e-306, 9.79101761e-307]]])

In [11]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Data Types for ndarrays

In [12]:
arr1 = np.array([1,2,3], dtype=np.float64)
arr1.dtype

dtype('float64')

In [13]:
arr2 = np.array([1,2,3], dtype=np. int32)
arr2.dtype

dtype('int32')

In [15]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [16]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [17]:
arr = np.array([3.7,-1.2,-2.6,0.5,12,10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12. , 10.1])

In [19]:
# astype을 사용하여 숫자로 변환
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

# 배열과 스칼라 간의 연산

In [20]:
# array는 스칼라.
arr= np.array([[1,2,3,],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
arr*arr
arr-arr
1/arr
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [23]:
# 뭐 모르겠으면 ? np 해서 도움말 확인

# 불리언 색인

In [24]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [25]:
data = randn(7,4)
data

array([[-0.75281487, -1.73490792,  0.74065036, -1.05397781],
       [ 0.14993462,  0.15626107, -1.84120349, -2.86209396],
       [ 0.72028852, -0.79493737,  0.91700665,  0.68300358],
       [-0.47865482, -0.43119724,  0.33327742, -0.42700548],
       [-1.37020045, -1.84417066,  1.69327244, -1.85491442],
       [-0.01544348, -0.90099997,  0.08654635, -0.44975123],
       [ 0.59275583,  0.5463181 ,  0.50468964,  1.81743813]])

In [26]:
names=='Bob'

array([ True, False, False,  True, False, False, False])

In [27]:
data[names=='Bob']

array([[-0.75281487, -1.73490792,  0.74065036, -1.05397781],
       [-0.47865482, -0.43119724,  0.33327742, -0.42700548]])

In [28]:
data[names == 'Bob', 2:]

array([[ 0.74065036, -1.05397781],
       [ 0.33327742, -0.42700548]])

# Fancy indexing

In [29]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [30]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [32]:
arr=np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [33]:
arr[[1,5,7,2,],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [34]:
arr[[1,5,7,2]][:,[0,3,1,2]] #좌변에서 행고르고, 우변에서 열 순서 변경

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [35]:
arr[np.ix_([1,5,7,2],[0,3,1,2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

# Transposing arrays and swapping axes

In [37]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [38]:
arr.T #행과 열을 바꿈

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [40]:
arr = np.random.randn(6,3)
arr

array([[ 1.51079505,  0.55161786,  1.05701548],
       [ 0.04253186, -0.26079253, -0.69345855],
       [ 0.1462936 ,  0.06429941,  0.92560614],
       [ 0.58202872,  0.48638589,  0.07215088],
       [ 0.62920439,  0.3916006 ,  0.4854146 ],
       [ 1.46473698, -0.16769248, -0.06677108]])

In [42]:
np.dot(arr.T,arr)

array([[5.18582247, 1.11555812, 1.95246673],
       [1.11555812, 0.79447245, 1.05981218],
       [1.95246673, 1.05981218, 2.70020468]])

In [45]:
arr=np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [46]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [47]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [48]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])